- name: Day 01
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    content: "{{ lookup('file', 'data/test1.in') }}"
    ret: 0
    idxl: 0
    idxr: 0
    left: 0
    right: 0
    temp_count: 0
    buffer: 0
    equals: false
    less: false
    greater: false
    prev: 0
  tasks:
    - name: Split test file
      ansible.builtin.set_fact:
        split_content: "{{ content.split('\n') | map('split', ' ')}}"
        arr0: []
        arr1: []
    - name: Generate arrays
      ansible.builtin.set_fact:
        arr0: "{{ arr0 + [item[0]] }}"
        arr1: "{{ arr1 + [item[-1]] }}"
      loop: "{{ split_content }}"
    - name: Sort arrays
      ansible.builtin.set_fact:
        arr0: "{{ arr0 | sort }}"
        arr1: "{{ arr1 | sort }}"
    - name: Loop through arrays
      ansible.builtin.set_fact:
        l: "{{ left }}"
        li: "{{ idxl }}"
        r: "{{ right }}"
        ri: "{{ idxr }}"
        p: "{{ arr0[prev | int] }}"
        buffer: |
          {{ (1 if equals and arr0[prev | int] != arr0[idxl | int] else (
            (buffer | int) + 1 if equals else ((buffer | int) if arr0[prev | int] == arr0[idxl | int] else 0))) }}
        ret: |
          {{ (ret | int) + (
            ((arr0[(idxl | int)] | int) * (buffer | int)) if not equals else 0)
          }}
        prev: "{{ idxl }}"
        idxl: "{{ ((idxl | int) + 1) if less else idxl }}"
        idxr: "{{ ((idxr | int) + 1) if (equals or greater) else idxr }}"
      vars:
        left: "{{ arr0[idxl | int] }}"
        right: "{{ arr1[idxr | int] }}"
        # l == r
        equals: "{{ (arr0[idxl | int] == arr1[idxr | int]) }}"
        # l < r
        less: "{{ (arr0[idxl | int] < arr1[idxr | int]) }}"
        # l > r
        greater: "{{ (arr0[idxl | int] > arr1[idxr | int]) }}"
      loop: "{{ query('sequence', 'start=1 end='+( (arr0 | length) + (arr1 | length) )|string) }}"
      when: (idxl | int) < (arr0 | length) and (idxr | int) < (arr1 | length)
      # register: loop_result
    # - name: Debug output
    #   ansible.builtin.debug:
    #     var: loop_result
    - name: Puzzle output
      ansible.builtin.debug:
        msg: "{{ idxl }} {{ idxr }} {{ ret | int }}"
